### PR TITLE
Update istore for pg16 compatibility

### PR DESCRIPTION
**Pull request by ridvankorkmaz**
@rapimo 's solution.

#ifndef SET_VARSIZE
/*
 * pg >= 16 reorganized the toastable header files
 * https://github.com/postgres/postgres/commit/d952373a987bad331c0e499463159dd142ced1ef
 * to ensure cross version compatibility we do a bit of a hack here */ #include "varatt.h"
#endif

### CODE REVIEW

**Review by za-arthur — CHANGES_REQUESTED** [review]
Thank you. Can you add Postgres 16 into the tests?
https://github.com/adjust/istore/blob/8a43a600addef22fe55a8b28dc9b7e3d8737630c/.github/workflows/main.yml#L14

**Comment by ridvankorkmaz** [comment]
Thanks @za-arthur  for review and suggestion, I added 16 test but failed, 
If you had any quick fix let me know, otherwise next week I have to investigate th reason.

**Comment by za-arthur** [comment]
Here is the error:

```
src/bigistore.c:765:50: error: passing argument 1 of ‘PointerGetDatum’ makes pointer from integer without a cast [-Werror=int-conversion]
```

**Comment by ridvankorkmaz** [comment]
> Thanks @za-arthur for review and suggestion, I added 16 test but failed, If you had any quick fix let me know, otherwise next week I have to investigate th reason.

Sorry @za-arthur, I confused with pg-base62, but I added 16 test to CI and this repo has failed with pg16 test, I will take care next week both.

**Pull request merged**
