### PR TITLE
add function join which joins istores

### PR DESCRIPTION
**Pull request by rapimo**
add function join which joins upto 5 istores on key and ouputs them as setof record 
with key, value[n]...
this shows better performance that LATERAL JOIN on key wich each(istore)
and is also possible with aggregates like SUM
e.g. SELECT (join(SUM(a), SUM(b), SUM(c))).\* FROM table

### CODE REVIEW

**Comment by rapimo** [comment]
@roa @chochkov @zeitgeist
happy to see any optimizations

**Comment by rapimo** [comment]
@zilder can you look into this, rebase to master so that we can eventually merge if we are happy?

**Comment by zilder** [comment]
Ok, will do

**Comment by zilder** [comment]
Created a new PR (#82) with rebased and a bit refactored version of this patch.

**Pull request closed without merging**
