### PR TITLE
Convert result/arguments to/from Datum when calling v1 pg functions.

### PR DESCRIPTION
**Pull request by alexeyklyukin**
Take a less cavalier approach to pg calling conventions and apply
DatumGetX/XGetDatum macros when calling PostgreSQL functions with
DirectFunctionCallN.

In particular, this fixes the "integer out of range" error when
calling istore constructor with negative values.

### CODE REVIEW

**Comment by alexeyklyukin** [comment]
@rapimo It seems the usual postgres tests are generated from the ruby specs; I've added the case for negative numbers to the spec, but couldn't figure out how to generate the sql and expected files out of it...

**Comment by rapimo** [comment]
I added the regression test using `rake dumbo:test:regression` 
and fix two minor typos, will go through it more deeply tomorrow

**Comment by zilder** [comment]
Hi @alexeyklyukin,

I agree with adding explicit conversions to/from Datum. Can you pls provide an example where absence of conversion caused "integer out of range"? ASAIU DatumGetIntX() and IntXGetDatum() don't do much on x64 systems, compiler itself should be able to add implicit conversions.

**Comment by alexeyklyukin** [comment]
@zilder the problem we've observed happened with:

https://github.com/adjust/istore/blob/c9703e439d5001e74328de392f05fbac7ba7782a/src/istore.c#L545

This code is activated when the istore is being composed from two arrays (keys and values), where there are several values for the same key and they should be summed together.

Now, the problem we've faced is when those values are negative, i.e.:
```
adjust_backend3=# SELECT istore(ARRAY[30,30], ARRAY[-1,-1]);
ERROR:  integer out of range
```

The code above would return a Datum containing 32-bit negative integer (-2), however, the datum itself is 64 bit, moreover, the value it is assigned to (`position->value`) is also a 64-bit integer. Hence, -2 is treated like a positive 64-bit value (4294967294) that causes an integer out of range somewhere else in the code.

**Comment by zilder** [comment]
I could reproduce this error only on postgres 10 (probably earlier versions also affected). Can confirm that it can be fixed by adding implicit conversion the result of `int4pl` to int32 (which then will implicitly be converted to int64 by compiler). Without it the result written to position->value would be:
```
(gdb) x/xg &position->value
0x12dfd48:	0x00000000fffffffe
```
Probably because of different implementation of many integer functions (including `int4pl`) starting from postgres 11 this problem doesn't occur on later versions. For instance this is what i get on pg12:
```
(gdb) x/xg &position->value
0x1542250:	0xfffffffffffffffe
```
i.e. a proper negative 64bit value.

Overall patch looks good to me, tests pass.

**Comment by alexeyklyukin** [comment]
That's the result of changes to the `Int32GetDatum`, called by PG_RETURN_INT32(x). In v10 and below it was defined as:
```
#define Int32GetDatum(X) ((Datum) SET_4_BYTES(X))
#define SET_4_BYTES(value)	(((Datum) (value)) & 0xffffffff)
```
in v11 and above,
```
#define Int32GetDatum(X) ((Datum) (X))
```

**Comment by alexeyklyukin** [comment]
But the problem is not on in Postgres, but on our side, v11 and above just masks it. Properly calling a from-Datum conversion function makes thing right on every Postgres version.

**Comment by alexeyklyukin** [comment]
So it seems I can merge it and then redeploy on all shards and replicas. The finalizer should pick it up for new sessions right away, but kpi-service instances connect via a transaction-mode pgbouncer, so pgbouncer pool should be drained to avoid re-using the old library.

**Comment by rapimo** [comment]
shouldn't an extension upgrade reload the library?

**Comment by nick-adjust** [comment]
If I read the source correctly, postgres doesn't do anything about it and after installing a new binary file one has to manually take care of all backends reloading it.

**Comment by alexeyklyukin** [comment]
@rapimo I don't think so. The upgrade does exactly what you specify in the upgrade script. As @nick-adjust says we have to make them reloaded manually.

**Comment by rapimo** [comment]
mmh to bad and renaming the library is probably not worth the effort though

**Comment by alexeyklyukin** [comment]
I think draining the pgbouncer pool is not a big problem and doesn't justify renaming the library, just wanted to confirm I don't miss anything in the deployment procedure.

**Comment by alexeyklyukin** [comment]
That has been reviewed by @zilder, merging it.

**Pull request merged**
